project:
  type: website
  output-dir: ../_site

website:
  title: "The Miserable Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/
  sidebar:
    contents:
      - section: "Chapters Decoded"
        contents:
          - blog-path-to-despair.qmd
          - blog-isolation.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
