project:
  type: book
  output-dir: ../_book

book:
  title: "Miserable"
  subtitle: "A Menu of Life Advice in Reverse"
  author: "The Reverse Maven"
  date: "12/25/2025"
  chapters:
    - index.qmd
    - part: "Part 1: The Kitchen (Foundations)"
      chapters:
        - foundations-intro.qmd
        - circadian-shuffle.qmd
        - nutritional-nihilism.qmd
        - sedentary-mastery.qmd
    - part: "Part 2: The Ingredients (Mindset)"
      chapters:
        - mechanics-of-structural-imbalance.qmd
        - fragility-of-comfort.qmd
        - peak-end-engineering.qmd
        - negative-filtering.qmd
        - vapid-goals.qmd
    - part: "Part 3: The Main Courses (Career & Finance)"
      chapters:
        - masterclass-of-the-dead-hour.qmd
    - part: "Part 4: Serving Others (Relationships)"
      chapters:
        - serving-of-isolation.qmd
        - broken-window-theory-of-despair.qmd
        - social-ledger-of-resentment.qmd
    - part: "Part 5: Dessert (The Meaning of it All)"
      chapters:
        - mirage-of-completion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt
